apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-backend
  labels:
    app: hello-backend
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hello-backend
      version: v1
  template:
    metadata:
      labels:
        app: hello-backend
        version: v1
    spec:
      containers:
      - name: hello-backend
        image: gcr.io/google-samples/hello-app:2.0
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: MESSAGE
          value: "Hello from Backend Service!"
---
apiVersion: v1
kind: Service
metadata:
  name: hello-backend
  labels:
    app: hello-backend
spec:
  ports:
  - port: 8080
    name: http
  selector:
    app: hello-backend
